#!/bin/bash

[[ -z "$2" ]] && echo "Waits for a number of jobs to finish, limiting the maximum background jobs"; echo "Usage: jwait {PID} {MAX_JOBS} [VERIFY_INTERVAL]"; exit 1

job-count(){
	echo "$(( $(grep "PPid:.*$1" /proc/[0-9]*/status | cut -d/ -f3 | wc -l) - 1 ))"
}

JOBS=$(job-count $1)
while [ $JOBS -gt $2 ]; do
    JOBS=$(job-count $1); sleep ${3:-0.5}
done
