#!/bin/bash

[[ ! -z "$2" ]] && TEXT=$2 || read TEXT

if [[ $1 == 'm' ]]; then
	dapi DELETE "/channels/$CONTEXT_CHANNEL/messages/$TEXT"
elif [[ $1 == 'c' ]]; then
	dapi DELETE "/channels/$TEXT"
elif [[ $1 == 'g' ]]; then
	dapi DELETE "/guilds/$TEXT"
elif [[ $1 == 'r' ]]; then
	dapi DELETE "/guilds/$CONTEXT_GUILD/roles/$TEXT"
elif [[ $1 == 'e' ]]; then
	dapi DELETE "/guilds/$CONTEXT_GUILD/emojis/$TEXT"
elif [[ $1 == 'i' ]]; then
	dapi DELETE "/invite/$TEXT"
else
	echo "Usage: $(basename $0) [(m)essage|(c)hannel|(g)uild|(r)ole|(e)moji|(i)nvite]" >&2
	exit 1
fi
