#!/bin/bash

case $1 in
'create'|'edit'|'leave'|'useradd'|'userdel'|'convert')
	[[ ! -z "$2" ]] && TEXT=$2 || read TEXT
	case $1 in
	'create')
		dapi POST "/users/$CONTEXT_AUTHOR/channels" "$TEXT" ;;
	'edit')
		dapi PATCH "/channels/$CONTEXT_CHANNEL" "$TEXT" ;;
	'leave')	
		dapi DELETE "/channels/$CONTEXT_CHANNEL" "$TEXT" ;;
	'useradd')
		dapi PUT "/channels/$CONTEXT_CHANNEL/recipients/$TEXT" ;;
	'userdel')
		dapi DELETE "/channels/$CONTEXT_CHANNEL/recipients/$TEXT" ;;
	'convert')
		dapi POST "/channels/$CONTEXT_CHANNEL/convert" ;;
	esac ;;
*)
	echo "Usage: $(basename $0) [COMMAND]" >&2
	echo "Avaliable commands:"
	echo "create [JSON]"
	echo "edit [JSON]"
	echo "leave [JSON]"

	echo "useradd [USERID]"
	echo "userdel [USERID]"

	echo "convert"
	exit 1 ;;
esac
