#!/usr/bin/python
import os
import sys
import time
import uuid

task = os.path.join(os.environ['MASH_TASKS'], str(uuid.uuid4().hex))
in_, out, err = f'{task}.in', f'{task}.out', f'{task}.err'
with open(in_, 'w') as f:
    f.write(sys.stdin.read())

while not (os.path.isfile(out) or os.path.isfile(err)):
    time.sleep(0.1) 

if os.path.isfile(out):
    sys.stdout.write(open(out).read())
    os.remove(out)
else:
    sys.stderr.write(open(err).read())
    os.remove(err)

os.remove(in_)

