#!/bin/bash

case $1 in
'get'|'new'|'del'|'list_ch'|'list_g')
	[[ ! -z "$2" ]] && TEXT=$2 || read TEXT
	case $1 in
	'get')
		INV=$(echo "$TEXT" | jq -r ".code")
		dapi GET "/invites/$INV" ;;
	'new')
		CHANNEL=$(echo "$TEXT" | jq -r ".channel")
		PAYLOAD=$(echo "$TEXT" | jq "del(.channel)")
		dapi POST "/channels/$CHANNEL/invites" "$PAYLOAD";;
	'del')
		INV=$(echo "$TEXT" | jq -r ".code")
		dapi DELETE "/invites/$INV" ;;
	'list_ch')
		CHANNEL=$(echo "$TEXT" | jq -r ".id")
		dapi GET "/channels/$CHANNEL/invites" ;;
	'list_g')
		GUILD=$(echo "$TEXT" | jq -r ".id")
		dapi GET "/guilds/$GUILD/invites" ;;
	esac ;;
*)
	echo "Usage: $(basename $0) {COMMAND} {JSON}" >&2
	echo "Manages the invite logic for the bot"
	echo ""
	echo "Every command accepts a string of JSON, as stdout or arg"
       	echo "Avaliable commands with their respective JSON keys:"
	echo ""
	echo "get: {code}"
	echo "    code: (string) the code of the invite"
	echo ""
	echo "new: {id} [max_age] [max_uses] [temporary] [unique]"
	echo "    id: (snowflake) the id of the channel"
	echo "    max_age: (integer) seconds for the invite to be valid, 0 for forever (default: 86400)"
	echo "    max_uses: (integer) max number of uses, 0 for unlimited (default: 0)"
	echo "    temporary: (boolean) if the invite only grants temporary membership (default:false)"
	echo "    unique: (boolean) if true, the invite can be used only one time (default: false)"
	echo ""
	echo "del: {code}"
	echo "    code: (string) the code of the invite"
	echo ""
	echo "list_ch: {id}"
	echo "    id: (snowflake) the id of the channel"
	echo ""
	echo "list_g: {id}"
	echo "    id: (snowflake) the id of the guild"
	exit 1 ;;
esac
