#!/bin/bash

[[ ! -z "$2" ]] && TEXT=$2 || read TEXT

if [[ $1 == 'k' ]]; then
	dapi 'DELETE' "/guilds/$CONTEXT_GUILD/members/$TEXT"
elif [[ $1 == 'b' ]]; then
	dapi 'PUT' "/guilds/$CONTEXT_GUILD/bans/$TEXT"
elif [[ $1 == 'u' ]]; then
	dapi 'DELETE' "/guilds/$CONTEXT_GUILD/bans/$TEXT"
else
	echo "Usage: $(basename $0) [(k)ick|(b)an|(u)nban]" >&2
	exit 1
fi
