#!/bin/bash

case $1 in
'get'|'send'|'edit'|'delete'|'bulk_delete'|'pin'|'unpin')
	[[ ! -z "$2" ]] && TEXT=$2 || read TEXT
	case $1 in
	'get')
		MSG=$(echo "$TEXT" | jq -r '.id')
		dapi GET "/channels/$CONTEXT_CHANNEL/messages/$MSG" ;;
	'send')
		PAYLOAD=$(echo "$TEXT" | jq 'del(.files)')
		FILES=$(echo "$TEXT" | jq '.files//empty')
		if [[ -z $FILES ]]; then
			dapi POST "/channels/$CONTEXT_CHANNEL/messages" "$PAYLOAD"
		else
			n=0
			FILES=$(echo "$FILES" | jq '.[]' | while read f; do echo -e " -F 'file$n=@$f'"; n=$(( $n+1 )); done)
			curl -s -X "POST" -A "$MASH_USERAGENT" -H "Authorization: Bot $MASH_TOKEN" -F "payload_json=$PAYLOAD" $FILES "https://discordapp.com/api/channels/$CONTEXT_CHANNEL/messages"
		fi ;;
	'edit')
		PAYLOAD=$(echo "$TEXT" | jq "del(.id)")
		MSG=$(echo "$TEXT" | jq -r ".id")
		dapi PATCH "/channels/$CONTEXT_CHANNEL/messages/$MSG" "$PAYLOAD" ;;
	'delete')
		MSG=$(echo "$TEXT" | jq -r ".id")
		dapi DELETE "/channels/$CONTEXT_CHANNEL/messages/$MSG" ;;
	'bulk_delete')
		dapi POST "/channels/$CONTEXT_CHANNEL/messages/bulk-delete" "$TEXT" ;;
	'pin')
		MSG=$(echo "$TEXT" | jq -r ".id")
		dapi PUT "/channels/$CONTEXT_CHANNEL/pins/$MSG" ;;
	'unpin')
		MSG=$(echo "$TEXT" | jq -r ".id")
		dapi DELETE "/channels/$CONTEXT_CHANNEL/pins/$MSG" ;;
	esac ;;
*)
	echo "Usage: $(basename $0) {COMMAND} {JSON}" >&2
	echo "Manages the message logic for the bot"
	echo ""
	echo "The commands are relative to the actual CONTEXT_CHANNEL"
	echo "Every command accepts a string of JSON, as stdout or arg"
       	echo "Avaliable commands with their respective JSON keys:"
	echo ""
	echo "get: {id}"
	echo "    id: (snowflake) the id of the message"
	echo ""
	echo "send: {content|embed|files} [nonce] [tts]"
	echo "    content: (string) the text of the message (0-2000)"
	echo "    embed: (embed object)  the embed of the message"
	echo "    files: (array) an array of paths, the files to be uploaded"
	echo "    nonce: (snowflake) the nonce of the message"
	echo "    tts: (boolean) whether the message is TTS or noe"
	echo ""
	echo "edit: {id} [content] [embed]"
	echo "    id: (snowflake) the id of the message"
	echo "    content: (string) the new text of the message (0-2000)"
	echo "    embed: (embed object) the new embed of the message"
	echo ""
	echo "delete: {id}"
	echo "    id: (snowflake) the id of the message"
	echo ""
	echo "bulk_delete: {messages}"
	echo "    messages: (array) an array of the message ids"
	echo ""
	echo "pin: {id}"
	echo "    id: (snowflake) the id of the message"
	echo ""
	echo "unpin: {id}"
	echo "    id: (snowflake) the id of the message"
	exit 1 ;;
esac
