#!/bin/bash

[[ ! -z "$2" ]] && TEXT=$2 || read TEXT

if [[ $1 == 'g' ]]; then
	dapi POST "/guilds" "$TEXT"
elif [[ $1 == 'c' ]]; then
	dapi POST "/guilds/$CONTEXT_GUILD/channels" "$TEXT"
elif [[ $1 == 'm' ]]; then
	dapi POST "/channels/$CONTEXT_CHANNEL/messages" "$TEXT"
elif [[ $1 == 'r' ]]; then
	dapi POST "/guilds/$CONTEXT_GUILD/roles" "$TEXT"
elif [[ $1 == 'e' ]]; then
	dapi POST "/guilds/$CONTEXT_GUILD/emojis" "$TEXT"
elif [[ $1 == 'i' ]]; then
	dapi POST "/channels/$CONTEXT_CHANNEL/invites" "$TEXT"
elif [[ $1 == 'w' ]]; then
	dapi POST "/channels/$CONTEXT_CHANNEL/webhooks" "$TEXT"
else
	echo "Usage: $(basename $0) [(g)uild|(c)hannel|(m)essage|(r)ole|(e)moji|(i)nvite|(w)ebhook]" >&2
	exit 1
fi
